---
  - name: Add a user
    hosts: all
    gather_facts: false
    tasks:
      - name: Add User
        user:
          name: "{{ morpheus['instance']['hostname'] }}"
          password: "xxxxxxx"
          state: present